spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uni-database
    password: user123
    username: user
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update